### ISSUE TITLE
感谢作者的mod，有一点点小建议

### ISSUE THREAD

**Issue by Brioal** [Enaium-StardewValleyMods/TeleportPoint#5]
这个mod真的太方便了，感谢作者的辛苦付出。
用的时候一个传送点占了屏幕的一行，传送点多了之后就需要翻页，每次有点麻烦，能不能把传送点改短一点，或者小一点，这样一页上就能显示更多的传送点，这样就更方便了

**Comment by Enaium** [comment]
你的分辨率是1080p吗

**Comment by Enaium** [comment]
更新EnaiumToolKit会根据屏幕和ui的大小显示更多的
